### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Wamy-Dev** [soosBot-com/Pagination#7]
Traceback (most recent call last):
  File "bot.py", line 10, in <module>
    import Paginator
  File "/home/hydra/.local/lib/python3.8/site-packages/Paginator.py", line 6, in <module>
    class Simple(discord.ui.View):
  File "/home/hydra/.local/lib/python3.8/site-packages/Paginator.py", line 44, in Simple
    async def start(self, ctx: typing.Union[discord.Interaction, commands.Context], pages: list[discord.Embed]):
TypeError: 'type' object is not subscriptable

**Comment by sooswastaken** [comment]
Thanks for creating an issue, I'll look into this tomorrow.

**Comment by sooswastaken** [comment]
Please reopen this issue with more information about this error.
